### ISSUE TITLE
resize wheel on window.resize

### ISSUE THREAD

**Issue by manattweb** [softwaretailoring/wheelnav#15]
I'm wanting to resize the wheel when the browser window is resized (narrowed). What must be manipulated using jQuery.resize?

**Comment by softwaretailoring** [comment]
I comitted a few changes.
Add this css to container div for reponsive behaviour:
```CSS
.wheelNav > svg {
    width: 100%;
    height: 100%;
}
```
You can check it on the test page: http://wheelnavjs.softwaretailoring.net/test
If it's working for you I'll create a new release.

**Comment by manattweb** [comment]
I downloaded the latest release and added the styles, but my application uses the piemenu implementation and bootstrap. You can view it here: http://devmerchants.save10.com. Thanks for your help. This really has my client distracted.

**Comment by softwaretailoring** [comment]
Did you try this?
```CSS
#piemenu > svg {
    width: 100%;
    height: 100%;
}
```
I didn't find 'wheelnavs10' class in your css files.
